[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Kenny Johansson <wirehell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
log = "0.4.8"
env_logger = "0.7.1"
